jQuery(document).ready(function(){
	jQuery("#wp-admin-bar-advanced-options").click(function(){
    	     jQuery("#menu-tools").toggle();
    	     jQuery("#menu-users").toggle();
    	     jQuery("#menu-settings").toggle();
    	     jQuery("#menu-appearance").toggle();
    	     jQuery("#menu-media").toggle();
    	     jQuery("#menu-comments").toggle();
    	     jQuery("#menu-plugins").toggle();
    	     jQuery("#wp-admin-bar-comments").toggle();
    	     jQuery("#wp-admin-bar-new-content").toggle();
    	     jQuery("#show-settings-link").toggle();
    	     jQuery("#contextual-help-link-wrap").toggle();
	});
});
